### PR TITLE
Allow C code to be profiled

### PR DESCRIPTION
**Pull request by DavidPoliakoff**
I don't know how to submit the changes I made to the C runtime, I can share those with you too. But now if you set "profile" to "true" in a C backend, you get profiling calls in currently just the update functions, but we can expand that.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
First step is for me to figure out how to contribute to the runtime, once we've got that done we can discuss polishing this thing up

**Comment by DavidPoliakoff** [comment]
never mind, found the directory where you host those files

**Comment by frothga** [comment]
Thanks a lot for working on this! Hopefully this won't be too critical, but here are some comments on the patch:

* The "profile" tag would fit best as $metadata.backend.c.profile. If it ever becomes more general than just C, it can go under $metadata.backend.all.profile.
* Rather than accessing the tag as a string, access it as a boolean: getOrDefault (false, "$metadata", "backend", "c", "profile"). Notice the absence of quotes around false.
* Is the gc-sections flag still deprecated in LLD (for example, on MacOS)? I checked their web site and they claim to fully support all LD options.
* The profile helper code (profile.cc/h) does not appear to be type-specific, so we can simply compile one version of it.
* The profile helper code appears to be platform-specific, so it may also require conditional building.
* Question: would it be possible to do the dynamic linking directly, without using helper code? The dependency on Kokkos is only created when the "profile" flag is set, so presumably the user asserts that Kokkos is available.
* If you're using Eclipse, consider loading the style-java.xml and style-cpp.xml files for this project.

**Comment by DavidPoliakoff** [comment]
@frothga, sincerely no worries, comments help this stuff be at the level it needs to. I also don't write Java, so if you're saying "maybe he had a reason to ______" I probably didn't

In order

- Will Do
- Yep
- I know this gave me an error somewhere, but don't know where. I tend to use relatively new gcc's
- I'm not sure how to implement this one, the compilation process is a bit opaque to me. Could you advise a bit?
- Good call, how do we do that?
- That's an option. The typical workflow I use for profiling code looks like this: compile a model with these hooks in place. Run it against a _set_ of tools, one after the other. If I link directly, that moves to "compile this model pointed at a tool," so you need the tool at model generation time, you can't run the model without the tool, and you changing tools requires regenerating a model. None of that is a problem for me, but my experience is that lazy-loading of tools is pretty helpful
- I've loaded style-java.xml, my guess is you need to hit a "format this thing" button or something though to make it format correctly. I know this is extremely basic, but could you tell me how to make Eclipse enforce that formatting?

**Comment by DavidPoliakoff** [comment]
Quick update (sorry, just checked it). A spack-built gcc 10.2 on a Linux'ish server doesn't know about gc-sections, and it appears we pass the option to GCC.

**Comment by frothga** [comment]
* gc-sections -- It seems that most but not all platforms support this flag. I'll modify the runtime builder to turn this off when necessary. Don't worry about making those changes, but please do put the flag back in for this patch.
* type-specific object files -- Leave this the way you have it now. I need to think about the best way to do it.
* platform-specific profiling helper code -- One way to handle this is to put #ifdef statements in profile.cc so that platform-specific code is only visible when it can be compiled successfully. The default case could be a set of empty functions that basically turn profiling into a no-op.
* dynamic linking -- If I understand this right, you are able to change out which tool to use simply by changing the environment variable, and all the tools use the same set of function calls. This makes a lot of sense, so let's keep it the way you have it now.
* For code that's mixed with existing Java code (JobC.java), you can place the caret in individual blocks and do: right-click (context menu) / Source / Format Element. In this case, please don't do a simple Format, because it will reformat the entire source file, which would undo any additional touch-ups I've done. For a new C file like profile.cc, you can do Format to update the entire file.
* BTW, it would be good to copy the NTESS copyright notice into the new source files. Just use the one from JobC.

**Comment by frothga** [comment]
Did a little digging on gc-sections. Since it is an ld option, it would actually be part of binutils rather than gcc.
@DavidPoliakoff, could you do a "ld --version" on that system that didn't accept the flag?

**Pull request merged**
